name: real_page_flip_example
description: "A minimal, clean example demonstrating the real_page_flip package."
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  real_page_flip:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
