/// Auto-generated by tool/generate_changelogs.dart — do not edit manually.
/// Deploy: cd example/workers/changelog-api && wrangler deploy

interface Env {}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Accept',
};

interface ChangelogEntry {
  version: string;
  versionCode: number;
  versionName: string;
  date: string;
  ko: { changes: string[] };
  en: { changes: string[] };
}

// START_CHANGELOGS
const changelogs: ChangelogEntry[] = [
    {
      version: "1.0.30+36",
      versionCode: 36,
      versionName: "1.0.30",
      date: "2026-06-27",
      ko: { changes: ["앱 업데이트 로그를 Cloudflare Worker API에서 실시간으로 받아오도록 개선"] },
      en: { changes: ["Release notes now fetched live from remote API instead of bundled-only"] },
    },
    {
      version: "1.0.29+35",
      versionCode: 35,
      versionName: "1.0.29",
      date: "2026-06-27",
      ko: { changes: ["설정 패널 스위치가 Android 네비게이션 바에 가려지던 문제 수정"] },
      en: { changes: ["Fixed settings panel switches hidden behind Android navigation bar"] },
    },
    {
      version: "1.0.28+34",
      versionCode: 34,
      versionName: "1.0.28",
      date: "2026-06-27",
      ko: { changes: ["햅틱 피드백이 완전히 출력되지 않던 긴급 버그 수정 (screenWidth 정규화 상수 오류)"] },
      en: { changes: ["Fixed haptic feedback not firing due to screen width normalization regression"] },
    },
    {
      version: "1.0.27+33",
      versionCode: 33,
      versionName: "1.0.27",
      date: "2026-06-26",
      ko: { changes: ["햅틱 피드백이 화면 크기에 따라 일관되지 않게 진동하던 문제 수정 (실제 기기 폭 기반 정규화)", "장시간 사용 시 메모리 사용량이 증가하던 문제 수정 (physics 엔진 자동 정리)", "goToPage 프로그래매틱 네비게이션 안정성 개선", "페이지플립 애니메이션 중 GPU compositing layer 오버헤드 감소"] },
      en: { changes: ["햅틱 피드백이 화면 크기에 따라 일관되지 않게 진동하던 문제 수정 (실제 기기 폭 기반 정규화)", "장시간 사용 시 메모리 사용량이 증가하던 문제 수정 (physics 엔진 자동 정리)", "goToPage 프로그래매틱 네비게이션 안정성 개선", "페이지플립 애니메이션 중 GPU compositing layer 오버헤드 감소"] },
    },
    {
      version: "1.0.26+32",
      versionCode: 32,
      versionName: "1.0.26",
      date: "2026-06-26",
      ko: { changes: ["네이티브 햅틱 엔진(CoreHaptics / Composition)을 적용하여 더욱 세밀하고 고급스러운 페이지 플립 질감(Smooth/Standard/Textured/Kraft) 물리 반응 구현"] },
      en: { changes: ["네이티브 햅틱 엔진(CoreHaptics / Composition)을 적용하여 더욱 세밀하고 고급스러운 페이지 플립 질감(Smooth/Standard/Textured/Kraft) 물리 반응 구현"] },
    },
    {
      version: "1.0.25+31",
      versionCode: 31,
      versionName: "1.0.25",
      date: "2026-06-25",
      ko: { changes: ["EPUB 목차(TOC) 페이지가 여러 페이지로 분할되어 표시되던 버그 수정 (epub:type=\"toc\" 감지 후 제외)", "가장자리 탭으로 챕터 경계 이동 시 페이지플립 제스처가 작동하지 않던 버그 수정 (PageFlipController 동기화)"] },
      en: { changes: ["EPUB 목차(TOC) 페이지가 여러 페이지로 분할되어 표시되던 버그 수정 (epub:type=\"toc\" 감지 후 제외)", "가장자리 탭으로 챕터 경계 이동 시 페이지플립 제스처가 작동하지 않던 버그 수정 (PageFlipController 동기화)"] },
    },
    {
      version: "1.0.24+30",
      versionCode: 30,
      versionName: "1.0.24",
      date: "2026-06-25",
      ko: { changes: ["UI 10개 언어 지원 (한국어, 영어, 스페인어, 필리핀어, 프랑스어, 인도네시아어, 포르투갈어, 중국어, 일본어)", "slang 기반 i18n 시스템 구축 (type-safe, YAML 기반 번역 관리)", "런타임 언어 전환 지원 (설정 저장)", "모든 하드코딩 문자열 context.t.* 마이그레이션", "l10n 테스트 13개 추가 (모든 로케일 키 존재 검증)", "위젯 테스트 TranslationProvider 호환성 수정"] },
      en: { changes: ["UI 10개 언어 지원 (한국어, 영어, 스페인어, 필리핀어, 프랑스어, 인도네시아어, 포르투갈어, 중국어, 일본어)", "slang 기반 i18n 시스템 구축 (type-safe, YAML 기반 번역 관리)", "런타임 언어 전환 지원 (설정 저장)", "모든 하드코딩 문자열 context.t.* 마이그레이션", "l10n 테스트 13개 추가 (모든 로케일 키 존재 검증)", "위젯 테스트 TranslationProvider 호환성 수정"] },
    },
    {
      version: "1.0.23+29",
      versionCode: 29,
      versionName: "1.0.23",
      date: "2026-06-24",
      ko: { changes: ["앱 아이콘을 새로운 Realbook 브랜드 로고로 교체 (Android/iOS 전체 해상도)"] },
      en: { changes: ["앱 아이콘을 새로운 Realbook 브랜드 로고로 교체 (Android/iOS 전체 해상도)"] },
    },
    {
      version: "1.0.22+28",
      versionCode: 28,
      versionName: "1.0.22",
      date: "2026-06-24",
      ko: { changes: ["Firebase Crashlytics + Sentry 이중 오류 리포팅 시스템 구축", "전역 오류 처리: Flutter 프레임워크 및 네이티브 영역 오류를 두 서비스에 동시 전송", "모든 데이터베이스/동기화/읽기 화면 작업에 오류 추적 적용", "SentryFlutter 초기화 (--dart-define SENTRY_DSN 설정 시 활성화)", "서재 데모 콘텐츠를 별도 파일로 분리", "PageFlipPainter/Clippers를 part 파일로 추출하여 코어 라이브러리 코드 정리", "햅틱 엔진 개선: iOS/Android 플랫폼별 질감 피드백 경로 분리, Weber-Fechner 비선형 진폭 곡선 적용", "SupabaseSyncClient 21개 단위 테스트 추가", "BookshelfSettingsPanel 15개 위젯 테스트 추가", "ReaderSettingsPanel 11개 위젯 테스트 추가", "DefaultPageFlipEffectHandler 20개 단위 테스트 추가", "기존 테스트 업데이트 및 리팩토링 대응"] },
      en: { changes: ["Firebase Crashlytics + Sentry 이중 오류 리포팅 시스템 구축", "전역 오류 처리: Flutter 프레임워크 및 네이티브 영역 오류를 두 서비스에 동시 전송", "모든 데이터베이스/동기화/읽기 화면 작업에 오류 추적 적용", "SentryFlutter 초기화 (--dart-define SENTRY_DSN 설정 시 활성화)", "서재 데모 콘텐츠를 별도 파일로 분리", "PageFlipPainter/Clippers를 part 파일로 추출하여 코어 라이브러리 코드 정리", "햅틱 엔진 개선: iOS/Android 플랫폼별 질감 피드백 경로 분리, Weber-Fechner 비선형 진폭 곡선 적용", "SupabaseSyncClient 21개 단위 테스트 추가", "BookshelfSettingsPanel 15개 위젯 테스트 추가", "ReaderSettingsPanel 11개 위젯 테스트 추가", "DefaultPageFlipEffectHandler 20개 단위 테스트 추가", "기존 테스트 업데이트 및 리팩토링 대응"] },
    },
    {
      version: "1.0.21+27",
      versionCode: 27,
      versionName: "1.0.21",
      date: "2026-06-24",
      ko: { changes: ["Play Store 리스팅 아이콘을 신규 브랜드 로고로 교체", "햅틱 진동 엔진 전면 재설계: 이벤트별 고유 진동 시그니처 적용 (시작/더블탭/미끄러짐/질감)", "물리 엔진 stickSlip 강도를 진동 세기에 반영하여 종이 넘김 촉감 현실화"] },
      en: { changes: ["Play Store 리스팅 아이콘을 신규 브랜드 로고로 교체", "햅틱 진동 엔진 전면 재설계: 이벤트별 고유 진동 시그니처 적용 (시작/더블탭/미끄러짐/질감)", "물리 엔진 stickSlip 강도를 진동 세기에 반영하여 종이 넘김 촉감 현실화"] },
    },
    {
      version: "1.0.20+26",
      versionCode: 26,
      versionName: "1.0.20",
      date: "2026-06-23",
      ko: { changes: ["페이지플립 햅틱 진동 출력 개선: Android에서 `Vibration.vibrate()` 모터 직접 구동으로 실제 진동 보장"] },
      en: { changes: ["페이지플립 햅틱 진동 출력 개선: Android에서 `Vibration.vibrate()` 모터 직접 구동으로 실제 진동 보장"] },
    },
    {
      version: "1.0.19+25",
      versionCode: 25,
      versionName: "1.0.19",
      date: "2026-06-23",
      ko: { changes: ["엄격한 품질 게이트 준수를 위한 코드 포맷팅 및 린트 경고 교정 완료"] },
      en: { changes: ["엄격한 품질 게이트 준수를 위한 코드 포맷팅 및 린트 경고 교정 완료"] },
    },
    {
      version: "1.0.18+24",
      versionCode: 24,
      versionName: "1.0.18",
      date: "2026-06-23",
      ko: { changes: ["1단보기 backward 페이지플립 foldX/flapMaterialWidth 방향을 forward와 통일하여 일관된 넘김 방향 보장"] },
      en: { changes: ["1단보기 backward 페이지플립 foldX/flapMaterialWidth 방향을 forward와 통일하여 일관된 넘김 방향 보장"] },
    },
    {
      version: "1.0.17+23",
      versionCode: 23,
      versionName: "1.0.17",
      date: "2026-06-22",
      ko: { changes: ["Bookshelf 화면 Sliver 기반 레이아웃으로 재설계 (BouncingScrollPhysics)", "ReaderTypography 도입: Noto Sans KR (UI), Outfit (기하학적), Serif/Sans (본문) 3가지 폰트 시스템", "BookshelfSettingsPanel 추가 (동기화 상태, 설정)", "다크 테마로 통일", "AdaptiveBannerAd initState → didChangeDependencies 이동으로 광고 중복 로드 방지", "테스트 환경에서 Google Fonts 대신 기본 폰트 사용하도록 fallback 처리"] },
      en: { changes: ["Bookshelf 화면 Sliver 기반 레이아웃으로 재설계 (BouncingScrollPhysics)", "ReaderTypography 도입: Noto Sans KR (UI), Outfit (기하학적), Serif/Sans (본문) 3가지 폰트 시스템", "BookshelfSettingsPanel 추가 (동기화 상태, 설정)", "다크 테마로 통일", "AdaptiveBannerAd initState → didChangeDependencies 이동으로 광고 중복 로드 방지", "테스트 환경에서 Google Fonts 대신 기본 폰트 사용하도록 fallback 처리"] },
    },
    {
      version: "1.0.15+21",
      versionCode: 21,
      versionName: "1.0.15",
      date: "2026-06-21",
      ko: { changes: ["앱 브랜딩 로고 전면 리뉴얼 및 전체 플랫폼(Android, iOS, macOS, Windows, Web) 앱 아이콘 교체 (기존 무한대 로고 폐기)", "신규 투명배경 WebP 로고 탑재", "페이지 플립 지오메트리 엔진 코드 가독성 개선 (파일 분할 및 린트 경고 12건 완전 해결)"] },
      en: { changes: ["앱 브랜딩 로고 전면 리뉴얼 및 전체 플랫폼(Android, iOS, macOS, Windows, Web) 앱 아이콘 교체 (기존 무한대 로고 폐기)", "신규 투명배경 WebP 로고 탑재", "페이지 플립 지오메트리 엔진 코드 가독성 개선 (파일 분할 및 린트 경고 12건 완전 해결)"] },
    },
    {
      version: "1.0.14+20",
      versionCode: 20,
      versionName: "1.0.14",
      date: "2026-06-21",
      ko: { changes: ["1단보기 햅틱 진동 세기 조절 버그 수정 및 최적화"] },
      en: { changes: ["1단보기 햅틱 진동 세기 조절 버그 수정 및 최적화"] },
    },
    {
      version: "1.0.13+19",
      versionCode: 19,
      versionName: "1.0.13",
      date: "2026-06-21",
      ko: { changes: ["앞으로 1단보기 페이지플립 콘텐츠 좌우 반전 버그 수정 (flipHorizontal 플래그 오류)"] },
      en: { changes: ["앞으로 1단보기 페이지플립 콘텐츠 좌우 반전 버그 수정 (flipHorizontal 플래그 오류)"] },
    },
    {
      version: "1.0.12+18",
      versionCode: 18,
      versionName: "1.0.12",
      date: "2026-06-21",
      ko: { changes: ["1단보기 forward 페이지플립 원래 방식으로 복원 (이동하는 접힘선)", "1단보기 backward는 제본선 고정 + 손가락 방향 일치 유지", "snapshot 렌더링 filterQuality 복원 (medium)", "불필요한 circular import 제거"] },
      en: { changes: ["1단보기 forward 페이지플립 원래 방식으로 복원 (이동하는 접힘선)", "1단보기 backward는 제본선 고정 + 손가락 방향 일치 유지", "snapshot 렌더링 filterQuality 복원 (medium)", "불필요한 circular import 제거"] },
    },
    {
      version: "1.0.11+17",
      versionCode: 17,
      versionName: "1.0.11",
      date: "2026-06-21",
      ko: { changes: ["1단보기 이전페이지 넘김 방향 수정 — 손가락(왼→오)과 flap 움직임이 반대였던 버그", "forward/backward 모두 왼쪽 제본선(x=0)에서 오른쪽으로 flap 확장 (flapRightOfFold 통일)"] },
      en: { changes: ["1단보기 이전페이지 넘김 방향 수정 — 손가락(왼→오)과 flap 움직임이 반대였던 버그", "forward/backward 모두 왼쪽 제본선(x=0)에서 오른쪽으로 flap 확장 (flapRightOfFold 통일)"] },
    },
    {
      version: "1.0.10+16",
      versionCode: 16,
      versionName: "1.0.10",
      date: "2026-06-21",
      ko: { changes: ["1단보기 접힘선(foldX)을 제본선에 고정 — 페이지가 뜯어지는 듯한 시각적 오류 해결", "forward: 스파인 왼쪽 고정(foldX=0), flap이 오른쪽으로 축소", "backward: 스파인 오른쪽 고정(foldX=pageWidth), flap이 왼쪽으로 성장", "flapRightOfFold 필드로 4개 모드 통합 (1단/2단 × forward/backward)", "각도 제한, 곡선 방향, clip path, paint gradient 일괄 수정", "geometry/clip/paint rendering/golden 테스트 전면 업데이트 (448개 통과)", "비공개테스트(closed alpha) 트랙 배포"] },
      en: { changes: ["1단보기 접힘선(foldX)을 제본선에 고정 — 페이지가 뜯어지는 듯한 시각적 오류 해결", "forward: 스파인 왼쪽 고정(foldX=0), flap이 오른쪽으로 축소", "backward: 스파인 오른쪽 고정(foldX=pageWidth), flap이 왼쪽으로 성장", "flapRightOfFold 필드로 4개 모드 통합 (1단/2단 × forward/backward)", "각도 제한, 곡선 방향, clip path, paint gradient 일괄 수정", "geometry/clip/paint rendering/golden 테스트 전면 업데이트 (448개 통과)", "비공개테스트(closed alpha) 트랙 배포"] },
    },
    {
      version: "1.0.9+15",
      versionCode: 15,
      versionName: "1.0.9",
      date: "2026-06-20",
      ko: { changes: ["backward flap clip bleed 방향 수정", "backward 단일 페이지 flap 전면 콘텐츠 수평 반전", "비공개테스트(closed alpha) 트랙 재배포"] },
      en: { changes: ["backward flap clip bleed 방향 수정", "backward 단일 페이지 flap 전면 콘텐츠 수평 반전", "비공개테스트(closed alpha) 트랙 재배포"] },
    },
    {
      version: "1.0.8+14",
      versionCode: 14,
      versionName: "1.0.8",
      date: "2026-06-20",
      ko: { changes: ["역방향 페이지 플립 flap이 foldX의 잘못된 방향에 위치하던 버그 수정", "freeEdgeX 필드 추가, buildFlapScreenClipPath backward용 별도 경로", "paint 메서드 gradient/fade 방향을 isForward에 따라 동적 전환", "backward flapLeft/freeEdgeX 검증 추가, golden 업데이트"] },
      en: { changes: ["역방향 페이지 플립 flap이 foldX의 잘못된 방향에 위치하던 버그 수정", "freeEdgeX 필드 추가, buildFlapScreenClipPath backward용 별도 경로", "paint 메서드 gradient/fade 방향을 isForward에 따라 동적 전환", "backward flapLeft/freeEdgeX 검증 추가, golden 업데이트"] },
    },
    {
      version: "1.0.7+13",
      versionCode: 13,
      versionName: "1.0.7",
      date: "2026-06-20",
      ko: { changes: ["역방향 페이지 플립 foldX 방향 수정", "floatProgress = 1 - dragProgress 반영"] },
      en: { changes: ["역방향 페이지 플립 foldX 방향 수정", "floatProgress = 1 - dragProgress 반영"] },
    },
    {
      version: "1.0.6+12",
      versionCode: 12,
      versionName: "1.0.6",
      date: "2026-06-20",
      ko: { changes: ["역방향 단일 페이지 플립에서 flap에 콘텐츠가 표시되지 않던 버그 수정"] },
      en: { changes: ["역방향 단일 페이지 플립에서 flap에 콘텐츠가 표시되지 않던 버그 수정"] },
    },
    {
      version: "1.0.5+10",
      versionCode: 10,
      versionName: "1.0.5",
      date: "2026-06-20",
      ko: { changes: ["역방향 단일 페이지 플립이 왼쪽이 아닌 오른쪽에서 시작하던 버그 수정", "bend shading / edge-fade 그래디언트 방향 일원화"] },
      en: { changes: ["역방향 단일 페이지 플립이 왼쪽이 아닌 오른쪽에서 시작하던 버그 수정", "bend shading / edge-fade 그래디언트 방향 일원화"] },
    },
    {
      version: "1.0.5+9",
      versionCode: 9,
      versionName: "1.0.5",
      date: "2026-06-20",
      ko: { changes: ["역방향 페이지 플립 foldX 방향 수정, clip/shading 방향 반전"] },
      en: { changes: ["역방향 페이지 플립 foldX 방향 수정, clip/shading 방향 반전"] },
    },
    {
      version: "1.0.4+7",
      versionCode: 7,
      versionName: "1.0.4",
      date: "2026-06-19",
      ko: { changes: ["64개 테스트 추가 (총 387개)"] },
      en: { changes: ["64개 테스트 추가 (총 387개)"] },
    },
    {
      version: "1.0.3+6",
      versionCode: 6,
      versionName: "1.0.3",
      date: "2026-06-19",
      ko: { changes: ["2단 보기에서 페이지 뒷면 콘텐츠 2.5D 구현"] },
      en: { changes: ["2단 보기에서 페이지 뒷면 콘텐츠 2.5D 구현"] },
    },
    {
      version: "1.0.2+5",
      versionCode: 5,
      versionName: "1.0.2",
      date: "2026-06-17",
      ko: { changes: ["페이지플립 접힌 면 클립 정렬 오차 수정", "Firebase 연동, Crashlytics 추가"] },
      en: { changes: ["페이지플립 접힌 면 클립 정렬 오차 수정", "Firebase 연동, Crashlytics 추가"] },
    },
    {
      version: "1.0.1+4",
      versionCode: 4,
      versionName: "1.0.1",
      date: "2026-06-17",
      ko: { changes: ["1단보기 페이지 넘김 시 빈 종이로 보이던 문제 수정", "광고를 서재 화면으로 이동"] },
      en: { changes: ["1단보기 페이지 넘김 시 빈 종이로 보이던 문제 수정", "광고를 서재 화면으로 이동"] },
    },
    {
      version: "1.0.0+3",
      versionCode: 3,
      versionName: "1.0.0",
      date: "2026-06-17",
      ko: { changes: ["Play Store 비공개테스트 첫 배포"] },
      en: { changes: ["Play Store 비공개테스트 첫 배포"] },
    },
  ];
// END_CHANGELOGS



export default {
  async fetch(request: Request, _env: Env): Promise<Response> {
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const url = new URL(request.url);

    if (url.pathname === '/api/changelog') {
      const versionCode = url.searchParams.get('versionCode');
      const after = url.searchParams.get('after');

      let result: ChangelogEntry[];

      if (versionCode) {
        const vc = parseInt(versionCode, 10);
        result = changelogs.filter(e => e.versionCode === vc);
      } else if (after) {
        const minVc = parseInt(after, 10);
        result = changelogs.filter(e => e.versionCode > minVc);
      } else {
        result = changelogs;
      }

      return new Response(JSON.stringify(result), {
        headers: {
          'Content-Type': 'application/json',
          'Cache-Control': 'public, max-age=3600',
          ...corsHeaders,
        },
      });
    }

    return new Response('Not Found', { status: 404 });
  },
};
